directories:
  output: release-fixed
  buildResources: build
appId: com.rawalite.app
productName: RawaLite
files:
  - filter:
      - package.json
      - dist-electron/
extraResources:
  - from: dist-web
buildDependenciesFromSource: false
asarUnpack:
  - node_modules/better-sqlite3/**/*
  - node_modules/bindings/**/*
  - node_modules/file-uri-to-path/**/*
  - '**/*.node'
icon: assets/icon.png
win:
  target:
    - target: nsis
      arch:
        - x64
  requestedExecutionLevel: asInvoker
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  perMachine: false
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: assets/icon.png
linux:
  target:
    - target: AppImage
      arch:
        - x64
  icon: assets/icon.png
electronVersion: 22.3.27
