directories:
  output: dist-release
  buildResources: build
appId: com.rawalite.app
productName: RawaLite
files:
  - filter:
      - dist-electron
      - package.json
      - node_modules/better-sqlite3/**/*
extraResources:
  - from: dist-web
extraFiles:
  - from: node_modules/better-sqlite3/build/Release/better_sqlite3.node
    to: resources/better_sqlite3.node
icon: assets/icon.png
win:
  target:
    - target: nsis
      arch:
        - x64
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: assets/icon.png
linux:
  target:
    - target: AppImage
      arch:
        - x64
  icon: assets/icon.png
electronVersion: 31.7.7
