directories:
  output: dist-release
  buildResources: build
appId: com.rawalite.app
productName: RawaLite
files:
  - filter:
      - package.json
      - dist-electron/
      - dist-web/
extraResources:
  - from: dist-web
buildDependenciesFromSource: false
nodeGypRebuild: false
asarUnpack:
  - node_modules/better-sqlite3/**/*
  - node_modules/bindings/**/*
  - '**/*.node'
electronVersion: 31.7.7
icon: assets/icon.png
win:
  target:
    - target: nsis
      arch:
        - x64
  requestedExecutionLevel: asInvoker
  icon: assets/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  perMachine: false
mac:
  target:
    - target: dmg
      arch:
        - x64
        - arm64
  icon: assets/icon.png
linux:
  target:
    - target: AppImage
      arch:
        - x64
  icon: assets/icon.png
