name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with: { version: 9 }
      - name: Install dependencies
        run: pnpm install
      - name: Enforce ESM (no CommonJS)
        shell: bash
        run: |
          if git grep -nE "(^|[^a-zA-Z0-9_])require\\(|module\\.exports" -- ':!node_modules/*' ; then
            echo "❌ CommonJS gefunden. Nur ESM erlaubt."; exit 1; fi
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Dist
        run: pnpm dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rawalite-artifacts
          path: |
            dist/*.exe
            dist/*.zip